/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package basics;

/**
 *
 * @author god
 */
public class Cdatafilescontent {
    static public String syntaxDefault = ""
        +"colors:Light:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"colors:DirectionalLight:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"colors:PointLight:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"colors:SpotLight:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:ExternProtoDeclare:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:ProtoDeclare:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:ProtoBody:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:ProtoInstance:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:ProtoInterface:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"protos:connect:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:TimeSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:ProxilitySensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:LoadSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:KeySensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:GeoTouchSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:TouchSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:VisibilitySensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:PlaneSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:CylinderSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:SphereSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:StringSensor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:Connect:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sensors:ROUTE:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Anchor:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Billboard:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:StaticGroup:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Switch:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Transform:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Inline:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:CADFace:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:CADPart:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:PointSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:LQuadSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Head:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"grouping:Scene:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sounds:sound:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"sounds:AudioClip:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:Arc2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:ArcClose2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:Circle2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:Disk2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:Polyne2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:Polypoint2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"2D shape:TriangleSet2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:NormalInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:OrientationInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:NurbsOrientationInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:PositionInterpolator2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:NurbsSurfaceInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:CoordinateInterpolator2D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:CoordinateInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:GeoPositionInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:ColorInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"interpolators:ScalarInterpolator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"bindable:Background:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"bindable:Fog:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"bindable:LocalFog:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"bindable:NavigationInfo:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"bindable:ViewPoint:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"components:component:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"components:shape:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"properties:FillPropertis:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"properties:LineProperties:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"properties:LOD:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"properties:Material:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"properties:Appearance:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:Composed3DTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:ComposedCubeMapTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:GeneratedCubeMapTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:Image3DTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:ImageCubeMapTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:ImageTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:MovieTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:MultiTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:MultiTextureCoordinate:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:MultiTextureTransform:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:NurbsTextureCoordinate:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:Pixel3DTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:PixelTexture:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureBackground:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureCoordinate:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureCoordinate3D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureCoordinate4D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureCoordinateGenerator:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureMatrixTransform:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureTansform:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"texture:TextureTransform3D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:DOCTYPE:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:PUBLIC:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:X3D:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:meta:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:MetadataDouble:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:MetadataFloat:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:MetadataInteger:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:MetadataSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"metatag:MetadataString:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:BooleanFilter:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:BooleanSequencer:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:BooleanToggle:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:BooleanTrigger:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:Normal:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:Coordinate:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:CoordinateDouble:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:IntegerSequencer:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:IntegerTrigger:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:Matrix3VertexAttribute:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"variables:Matrix4VertexAttribute:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"shaders:ComposedShader:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"shaders:PackagedShader:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"shaders:ProgramShader:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"shaders:ShaderPart:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"shaders:ShaderProgram:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:Box:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:Cone:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:Cylinder:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:Sphere:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:ElevationGrid:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:Text:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:TriangleFanSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:TriangleSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:TriangleStripSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"3D shape:IndexedFaceSet:no description available:<H1><b>Command</b></H1><br/><br/><i>no description available</i>\n"
        +"preprocessor:Menlo|12|false|false|255,255,255|153,153,153\n"
        +"tag name:Menlo|12|false|false|255,255,255|0,0,255\n"
        +"characters:Menlo|12|false|false|255,255,255|220,0,156\n"
        +"decimal values:Menlo|12|false|false|255,255,255|100,0,200\n"
        +"comment:Menlo|12|false|true|255,255,255|0,128,0\n"
        +"comment EOL:Menlo|12|false|true|255,255,255|0,128,0\n"
        +"function:Menlo|12|false|false|255,255,255|173,128,0\n"
        +"identifiers:Menlo|12|false|false|255,255,255|0,0,0\n"
        +"variables:Menlo|12|false|false|255,255,255|255,153,0\n"
        +"reserved words:Menlo|12|true|false|255,255,255|0,0,255\n"
        +"comment documentation:Menlo|12|false|true|255,255,255|164,0,0\n"
        +"boolean values:Menlo|12|false|false|255,255,255|100,0,200\n"
        +"hexadecimal values:Menlo|12|false|false|255,255,255|100,0,200\n"
        +"tag delimiter:Menlo|12|false|false|255,255,255|255,0,0\n"
        +"separators:Menlo|12|false|false|255,255,255|255,0,0\n"
        +"operators:Menlo|12|false|false|255,255,255|128,64,64\n"
        +"tag attribute:Menlo|12|false|false|255,255,255|63,127,127\n"
        +"default:Menlo|12|false|false|255,255,255|255,0,0\n"
        +"float values:Menlo|12|false|false|255,255,255|100,0,200\n"
        +"data types:Menlo|12|false|false|255,255,255|0,128,128\n"
        +"white spaces:Menlo|12|false|false|255,255,255|255,0,0\n"
        +"string values:Menlo|12|false|false|255,255,255|220,0,156\n"
        +"backquotes:Menlo|12|false|false|255,255,255|220,0,156\n";
    public static String autosaveDefault = ""
            +"F:10\n"
            +"<?xml version='1.0' encoding='UTF-8'?>\n"
            +"<!DOCTYPE X3D PUBLIC \"ISO//Web3D//DTD X3D 3.1//EN\" \"http://www.web3d.org/specifications/x3d-3.1.dtd\">\n"
            +"<X3D profile='Immersive' version='3.0'>\n"
            +"<Head>\n"
            +"	<meta name='title' 		key='_title'></meta>\n"
            +"	<meta name='created' 	key='24/05/2011'></meta>\n"
            +"	<meta name='description' key='_description'></meta>\n"
            +"	<meta name='generator' 	key='Submarine X3D'></meta>\n"
            +"</Head>\n"
            +"<Scene>\n"
            +"	<NavigationInfo type='\"EXAMINE\",\"ANY\"'></NavigationInfo>\n"
            +"	<!-- put here your code! -->\n"
            +"</Scene>\n"
            +"</X3D>\n";
    public static String errorsDefault = ""
            +"UPDATEERR:Update's error:<html>It seems you are <b>not</b> connected to the Internet. Do you know that updates check need a connection?</html>\n"
            +"CONFIGERR:Configuration's error:<html>I can't save/load the configuration's file. Seems like there are some permission's problem!</html>\n"
            +"THREADERR:Thread's error:<html>Something goes wrong in the System's sleep process, but I can assure you this is not my fault!</html>\n"
            +"COMMUNERR:Communication's error:<html>I can't estabilish a communication channel with the server. Are you connected to the Internet?</html>\n"
            +"EMPTIEERR:Empty fields:<html>It seems you have leaved some empty fields in there. Please complete the module before proceed!</html>\n"
            +"SAVINGERR:Saving error:<html>I can't save your file in this place of your computer. Very sorry dude, choose another location!</html>\n"
            +"LOADINERR:Loading error:<html>I can't load your file from this place of your computer. Very sorry dude, choose another file or move it to another location!</html>\n"
            +"TEXTURERR:Disabling local textures:<html>You choose to not use local textures so I will disabled this function for you and I will use absolute paths</html>\n"
            +"RECEIVERR:Receiving error:<html>I can't save the received file in the application's place of your computer. Very sorry dude!</html>\n"
            +"UPLOADERR:Uploading error:<html>I can't upload the file from the application's place of your computer. Very sorry dude!</html>\n"
            +"PREVIEERR:Preview application's error:<html>It seems I've got some problems starting your preview application. Please, choose another one from configuration's panel!</html>\n"
            +"DOCUMEERR:General Document's error:<html>I can't write/read in the tab's embedded document. Seems like you find a very big bug! Please contact my creator <a href=\"mailto:nardinocchi@psychogames.net\">here</a>.</html>\n"
            +"TOKENIERR:General Tokenizer's error:<html>The tokenizer generate a general exception. Seems like you find a very big bug! Please contact my creator <a href=\"mailto:nardinocchi@psychogames.net\">here</a>.</html>\n"
            +"SYNTAXERR:Configuration's syntax error:<html>I can't understand the configuration's syntax. Did you put your dirty hands inside this files? Please, reinstall me!</html>\n"
            +"PASSWDERR:Wrong username or password:<html>It seems you write a wrong username or password. Please, try again!</html>\n"
            +"PROJECERR:Project's access error:<html>It seems you have no permission to access this project. Please, try again.</html>\n"
            +"SERVERERR:Server is going to be crazy:<html>The Server is going <b>slightly mad</b>! It writes non-sense commands and I can't understand his sentences!</html>\n"
            +"SELECTERR:No selected file:<html>It seems you have not selected any project's file. Please, select the file you want to delete before execute this action!</html>\n";
}
